<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="CPC-komal-XCL5G" failures="1" tests="3" name="Error Validation Test" time="35.541" errors="0" timestamp="2023-06-13T13:33:33 IST">
  <testcase classname="KomalGupta.Tests.ErrorValidation" name="LoginErrorValidation" time="2.046">
    <skipped/>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="KomalGupta.Tests.ErrorValidation" name="LoginErrorValidation" time="2.212">
    <failure type="java.lang.AssertionError" message="expected [Your User ID or Password is incorrect. Try again.] but found [Your User ID Password is incorrect. Try again.]">
      <![CDATA[java.lang.AssertionError: expected [Your User ID or Password is incorrect. Try again.] but found [Your User ID Password is incorrect. Try again.]
at KomalGupta.Tests.ErrorValidation.LoginErrorValidation(ErrorValidation.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- LoginErrorValidation -->
  <testcase classname="KomalGupta.Tests.ErrorValidation" name="ProductErrorValidation" time="13.078"/>
</testsuite> <!-- Error Validation Test -->
